### ISSUE TITLE
error: 'deallocate(capacity:)' is deprecated

### ISSUE THREAD

**Issue by mssun** [mattrubin/OneTimePassword#166]
I'm using Xcode version 9.3 (9E145) to build from Carthage.

```
Checkouts/OneTimePassword/Sources/Crypto.swift:33:20: error: 'deallocate(capacity:)' is deprecated: Swift currently only supports freeing entire heap blocks, use deallocate() instead
    defer { macOut.deallocate(capacity: hashLength) }
                   ^

** ARCHIVE FAILED **


The following build commands failed:
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
        CompileSwift normal arm64
(2 failures)
```

**Comment by mattrubin** [comment]
[OneTimePassword 3.1.1](https://github.com/mattrubin/OneTimePassword/releases/tag/3.1.1) is now available, and should work with Swift 4.1 and Xcode 9.3. Please let me know if you encounter any more issues.

**Comment by mssun** [comment]
It works. Thanks.
